---
# roles/install_iis/tasks/main.yml

- name: Install IIS
  win_feature:
    name: "Web-Server"
    state: present
    include_sub_features: yes
    include_management_tools: no
    restart: yes

- name: Create default website directory
  win_file:
    path: "C:\\inetpub\\wwwroot"
    state: directory

- name: Copy default index.html
  win_copy:
    src: "files/default.html"
    dest: "C:\\inetpub\\wwwroot\\index.html"

- name: Open port 80 for HTTP traffic
  win_firewall_rule:
    name: "Allow HTTP"
    action: Allow
    direction: In
    localport: 80
    protocol: Tcp
    enabled: yes
    state: present
