---
# roles/install_splunk_standalone/tasks/main.yml

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes
  become: yes

- name: Ensure Docker is started
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Pull Splunk Docker image
  docker_image:
    name: splunk/splunk
    tag: latest
    source: pull

- name: Run Splunk container with certificate
  command: docker run -d -p 8000:8000 -e SPLUNK_START_ARGS="--accept-license" -e SPLUNK_PASSWORD='{{ splunk_admin_password }}' splunk/splunk:latest
  register: splunk

