---
# roles/run_splunk/tasks/main.yml

- name: Pull Splunk Docker image
  docker_image:
    name: splunk/splunk
    tag: latest
    source: pull

- name: Verify Certificate File
  stat:
    path: /etc/splunk/certs/cacert.pem
  register: cert_file

- name: Debug Certificate Path
  debug:
    var: cert_file

- name: Run Splunk container with certificate
  docker_container:
    name: splunk
    image: splunk/splunk:latest
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
      - "8089:8089"
      - "9997:9997"
    env:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "{{ splunk_password }}"
    volumes:
      - /opt/splunk:/opt/splunk
      - /etc/splunk/certs/cacert.pem:/etc/splunk/cert.pem
 
