---
# roles/export_cert/tasks/main.yml

- name: Export certificate from Windows Server
  hosts: windows
  tasks:
    - name: Copy certificate to Linux server
      win_copy:
        src: "C:\\path\\to\\certificate.cer"
        dest: "/tmp/certificate.cer"
