---
# roles/transfer_cert/tasks/main.yml

- name: Create directory for Splunk certificates
  file:
    path: /opt/splunk/certs
    state: directory
    mode: '0755'

- name: Copy CA certificate to Ubuntu EC2
  copy:
    src: /home/matan/Active-Directory/ansible/roles/install_splunk_standalone/files/My_Cert.pem
    dest: /opt/splunk/certs/My_Cert.pem
