---
# roles/transfer_cert/tasks/main.yml

- name: Copy certificate to EC2
  copy:
    src: ~/Active-Directory/ansible/roles/install_splunk_standalone/files/My_Cert.pfx
    dest: /etc/ssl/certs/splunk_cert.pem
