---
# roles/install_splunk/tasks/main.yml

- name: Create Splunk group
  group:
    name: splunk
    state: present

- name: Create Splunk user
  user:
    name: splunk
    group: splunk
    createhome: no
    shell: /bin/false

- name: Download Splunk
  get_url:
    url: "https://download.splunk.com/products/splunk/releases/8.2.0/linux/splunk-8.2.0-a7f645ddaf91-Linux-x86_64.tgz"
    dest: "/tmp/splunk-8.2.0-a7f645ddaf91-Linux-x86_64.tgz"

- name: Extract Splunk
  unarchive:
    src: "/tmp/splunk-8.2.0-a7f645ddaf91-Linux-x86_64.tgz"
    dest: /opt
    creates: "/opt/splunk/bin/splunk"
    remote_src: yes

- name: Change ownership of Splunk directory
  file:
    path: /opt/splunk
    state: directory
    owner: splunk
    group: splunk
    recurse: yes

- name: Start Splunk
  command: "/opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd your_password"
  become: yes

- name: Enable Splunk boot-start
  command: "/opt/splunk/bin/splunk enable boot-start -user splunk"
  become: yes

- name: Transfer CA certificate to Linux host
  copy:
    src: /tmp/MyCARootCert.cer
    dest: /etc/ssl/certs/splunkcert.pem
    owner: root
    group: root
    mode: '0644'

- name: Configure Splunk to use the certificate
  lineinfile:
    path: /opt/splunk/etc/system/local/server.conf
    regexp: '^(\s*enableSplunkdSSL =).*'
    line: 'enableSplunkdSSL = true'
    create: yes

- name: Set Splunk SSL password
  lineinfile:
    path: /opt/splunk/etc/system/local/server.conf
    regexp: '^(\s*sslPassword =).*'
    line: 'sslPassword = your_password'
    create: yes

- name: Set Splunk certificate path
  lineinfile:
    path: /opt/splunk/etc/system/local/server.conf
    regexp: '^(\s*serverCert =).*'
    line: 'serverCert = /etc/ssl/certs/splunkcert.pem'
    create: yes

- name: Restart Splunk
  command: "/opt/splunk/bin/splunk restart"
  become: yes
