---
- name: Install AD CS and Certification Authority
  win_feature:
    name:
      - ADCS-Cert-Authority
      - ADCS-Web-Enrollment
    state: present

- name: Configure CAPolicy.inf
  template:
    src: CAPolicy.inf.j2
    dest: C:\Windows\CAPolicy.inf

- name: Install Certification Authority
  win_shell: |
    $ErrorActionPreference = "Stop"
    $password = ConvertTo-SecureString -String "MesstVS0k9JwrU1Y" -AsPlainText -Force
    Install-AdcsCertificationAuthority -CAType StandaloneRootCA -CACommonName "RootCA" -KeyLength 2048 -HashAlgorithmName "SHA256"
  args:
    executable: powershell.exe
  register: install_ca

- name: Ensure Certification Authority service is running
  win_service:
    name: CertSvc
    start_mode: auto
    state: started
  when: install_ca is succeeded

- name: Debug Install CA
  debug:
    var: install_ca.stderr_lines
  when: install_ca is failed
