---
- name: Install and configure Active Directory Domain Services and Install Microsoft Certification Authority on Windows Server
  hosts: windows
  roles:
#    - ad
#    - ca
#    - export_cert
#    - install_iis

- name: Transfer certificate to Ubuntu EC2 
  hosts: linux 
  become: yes 
  roles: 
    - transfer_cert

- name: Install Docker on Ubuntu EC2
  hosts: linux 
  become: yes 
  roles: 
    - install_docker

- name: Install Splunk Standalone on Linux
  hosts: linux
  become: yes
  vars:
    splunk_password: "{{ lookup('env', 'SPLUNK_ADMIN') }}"
    splunk_build_type: "latest" 
  roles:
    - splunk_common

- name: Install Splunk Standalone on Linux
  hosts: linux
  become: yes
  roles:
    - add_cert_to_splunk
