---
- name: Install and configure Active Directory Domain Services and Install Microsoft Certification Authority on Windows Server
  hosts: windows
  roles:
    - ad
    - ca
    - export_cert
    - install_iis


- name: Install Splunk Standalone on Linux
  hosts: linux
  become: yes
  vars:
    splunk_password: "{{ lookup('env', 'SPLUNK_ADMIN') }}"
    splunk_build_type: "latest" 
  roles:
    - transfer_cert
    - install_docker
    - install_splunk_standalone


