---
- name: Install and configure Active Directory Domain Services and Install Microsoft Certification Authority on Windows Server
  hosts: windows
  roles:
#    - ad
#    - ca
#    - export_cert
#    - install_iis

- name: Install Splunk Standalone on Linux
  hosts: linux
  become: yes
  vars:
    splunk_image: "splunk/splunk:latest"
    splunk_password: "{{ lookup('env', 'SPLUNK_ADMIN') }}"
    ca_cert_path: "/home/ubuntu/cert/My_Cert.pfx"
    container_name: "splunk_container"
    splunk_build_type: "enterprise"
  
  roles:
    - transfer_cert
    - install_splunk_standalone
