---
- name: Install and configure Active Directory Domain Services and Install Microsoft Certification Authority on Windows Server
  hosts: windows
#  vars: 
#    domain_name: "rafael.local" 
#    safe_mode_password: "{{ lookup('env', 'AD_SAFE') }}"
  roles:
#    - ad
#    - ca
#    - export_cert
#    - install_iis

- name: Install Splunk Standalone on Linux
  hosts: linux
  become: yes
  vars:
    splunk_admin_password: "{{ lookup('env', 'SPLUNK_ADMIN') }}"
  roles:
    - install_splunk_standalone
